dubbo:
  application:
    name: dubbo-demo-provider
    logger: log4j
  protocol:
    name: dubbo
    port: 20880
    accesslog: "true"
  registry:
    address: zookeeper://10.1.100.98:2181
  scan:
    base-packages: com.imain.dubbodemo

server:
  port: 8081